### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by omega500** [Seejayz/WorldofwarcraftArmory#1]
I have the last revision of the trinitycore repo and i have this errors.

/home/trinity/compi/TrinityCore/src/server/game/Battlegrounds/Battleground.cpp: In member function 'void Battleground::EndBattleground(uint32)':
/home/trinity/compi/TrinityCore/src/server/game/Battlegrounds/Battleground.cpp:759: error: 'class QueryResult' has no member named 'release'
compilation terminated due to -Wfatal-errors.
make[2]: **\* [src/server/game/CMakeFiles/game.dir/Battlegrounds/Battleground.cpp.o] Erreur 1
make[2]: **\* Attente des tâches non terminées....
[ 19%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Spells/spell_generic.cpp.o
/home/trinity/compi/TrinityCore/src/server/scripts/Spells/spell_generic.cpp: In member function 'void spell_gen_luck_of_the_draw::spell_gen_luck_of_the_draw_AuraScript::Update(AuraEffect*)':
/home/trinity/compi/TrinityCore/src/server/scripts/Spells/spell_generic.cpp:1516: warning: comparison between signed and unsigned integer expressions

Sorry if i do it wrong i just want to share my problem and help if someone else have them too

**Comment by Seejayz** [comment]
I'll have to take a look at this.

**Comment by omega500** [comment]
Thx for your work !

**Comment by Seejayz** [comment]
Try compile now ^^

**Comment by lasoto** [comment]
again .....
E:\Win-Files\fresh\TrinityCore\src\server\game\Achievements\AchievementMgr.cpp(2045): error C2039: 'CreateWowarmoryFeed' : is not a member of 'Player'
          E:/Win-Files/fresh/TrinityCore/src/server/game/Entities/Player\Player.h(1075) : see declaration of 'Player'
E:\Win-Files\fresh\TrinityCore\src\server\game\Entities\Item\Item.cpp(286): error C2039: 'CreateWowarmoryFeed' : is not a member of 'Player'
          E:/Win-Files/fresh/TrinityCore/src/server/game/Entities/Player\Player.h(1075) : see declaration of 'Player'
E:\Win-Files\fresh\TrinityCore\src\server\game\Entities\Player\Player.cpp(18940): error C3861: 'InitWowarmoryFeeds': identifier not found
E:\Win-Files\fresh\TrinityCore\src\server\game\Entities\Player\Player.cpp(25551): error C2039: 'InitWowarmoryFeeds' : is not a member of 'Player'
          e:\win-files\fresh\trinitycore\src\server\game\entities\player\Player.h(1075) : see declaration of 'Player'
E:\Win-Files\fresh\TrinityCore\src\server\game\Entities\Player\Player.cpp(25553): error C2065: 'm_wowarmory_feeds' : undeclared identifier
E:\Win-Files\fresh\TrinityCore\src\server\game\Entities\Player\Player.cpp(25553): error C2228: left of '.clear' must have class/struct/union
          type is ''unknown-type''
E:\Win-Files\fresh\TrinityCore\src\server\game\Entities\Player\Player.cpp(25556): error C2039: 'CreateWowarmoryFeed' : is not a member of 'Player'
          e:\win-files\fresh\trinitycore\src\server\game\entities\player\Player.h(1075) : see declaration of 'Player'
E:\Win-Files\fresh\TrinityCore\src\server\game\Entities\Player\Player.cpp(25562): error C3861: 'GetGUIDLow': identifier not found
E:\Win-Files\fresh\TrinityCore\src\server\game\Entities\Player\Player.cpp(25574): error C3861: 'GetGUIDLow': identifier not found
E:\Win-Files\fresh\TrinityCore\src\server\game\Entities\Player\Player.cpp(25578): error C3861: 'GetGUIDLow': identifier not found
E:\Win-Files\fresh\TrinityCore\src\server\game\Entities\Player\Player.cpp(25581): error C2227: left of '->GetDifficulty' must point to class/struct/union/generic type
          type is ''unknown-type''
E:\Win-Files\fresh\TrinityCore\src\server\game\Entities\Player\Player.cpp(25581): error C3861: 'GetMap': identifier not found
E:\Win-Files\fresh\TrinityCore\src\server\game\Entities\Player\Player.cpp(25587): error C2065: 'm_wowarmory_feeds' : undeclared identifier
E:\Win-Files\fresh\TrinityCore\src\server\game\Entities\Player\Player.cpp(25587): error C2228: left of '.push_back' must have class/struct/union
          type is ''unknown-type''
E:\Win-Files\fresh\TrinityCore\src\server\game\Entities\Unit\Unit.cpp(15667): error C2039: 'CreateWowarmoryFeed' : is not a member of 'Player'
          E:/Win-Files/fresh/TrinityCore/src/server/game/Entities/Player\Player.h(1075) : see declaration of 'Player'

**Comment by Seejayz** [comment]
Works fine for me :/

**Comment by lasoto** [comment]
:O i use latest version of trinitycore ....
i try add patch manual  :S then i post here

**Comment by omega500** [comment]
I will try it

**Comment by Seejayz** [comment]
Pull source now, new patch, https://github.com/Seejayz/WorldofwarcraftArmory/commit/5fbe20a0b4a77169c93a2f16f3477391bfe19e63

**Comment by omega500** [comment]
This work great, thanks !
