### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by raspotidza** [Seejayz/WorldofwarcraftArmory#2]
When i tri to compile with the last trinitycore 09/04 i've this error

1>------ Début de la génération : Projet : ZERO_CHECK, Configuration : Release Win32 ------
2>------ Début de la génération : Projet : revision.h, Configuration : Release Win32 ------
2>  
2>  -- WARNING - Missing or outdated git - did you forget to install a recent version?
2>  -- WARNING - Observe that for revision hash/date to work you need at least version 1.7
2>  -- WARNING - Missing repository tags - you may need to pull tags with git fetch -t
2>  -- WARNING - Continuing anyway - note that the versionstring will be set to 0000-00-00 00:00:00 (Archived)
3>------ Début de la génération : Projet : game, Configuration : Release Win32 ------
3>  AchievementMgr.cpp
3>  Item.cpp
3>  Player.cpp
3>  Unit.cpp
3>C:\Users\Schitan996\Desktop\TC_2_090412\src\server\game\Entities\Item\Item.cpp(286): error C2039: 'CreateWowarmoryFeed' : n'est pas membre de 'Player'
3>          C:/Users/Schitan996/Desktop/TC_2_090412/src/server/game/Entities/Player\Player.h(1075) : voir la déclaration de 'Player'
3>C:\Users\Schitan996\Desktop\TC_2_090412\src\server\game\Achievements\AchievementMgr.cpp(2045): error C2039: 'CreateWowarmoryFeed' : n'est pas membre de 'Player'
3>          C:/Users/Schitan996/Desktop/TC_2_090412/src/server/game/Entities/Player\Player.h(1075) : voir la déclaration de 'Player'
3>C:\Users\Schitan996\Desktop\TC_2_090412\src\server\game\Entities\Unit\Unit.cpp(15667): error C2039: 'CreateWowarmoryFeed' : n'est pas membre de 'Player'
3>          C:/Users/Schitan996/Desktop/TC_2_090412/src/server/game/Entities/Player\Player.h(1075) : voir la déclaration de 'Player'
3>C:\Users\Schitan996\Desktop\TC_2_090412\src\server\game\Entities\Player\Player.cpp(18940): error C3861: 'InitWowarmoryFeeds' : identificateur introuvable
3>C:\Users\Schitan996\Desktop\TC_2_090412\src\server\game\Entities\Player\Player.cpp(25551): error C2039: 'InitWowarmoryFeeds' : n'est pas membre de 'Player'
3>          c:\users\schitan996\desktop\tc_2_090412\src\server\game\entities\player\Player.h(1075) : voir la déclaration de 'Player'
3>C:\Users\Schitan996\Desktop\TC_2_090412\src\server\game\Entities\Player\Player.cpp(25553): error C2065: 'm_wowarmory_feeds' : identificateur non déclaré
3>C:\Users\Schitan996\Desktop\TC_2_090412\src\server\game\Entities\Player\Player.cpp(25553): error C2228: la partie gauche de '.clear' doit avoir un class/struct/union
3>          le type est ''unknown-type''
3>C:\Users\Schitan996\Desktop\TC_2_090412\src\server\game\Entities\Player\Player.cpp(25556): error C2039: 'CreateWowarmoryFeed' : n'est pas membre de 'Player'
3>          c:\users\schitan996\desktop\tc_2_090412\src\server\game\entities\player\Player.h(1075) : voir la déclaration de 'Player'
3>C:\Users\Schitan996\Desktop\TC_2_090412\src\server\game\Entities\Player\Player.cpp(25562): error C3861: 'GetGUIDLow' : identificateur introuvable
3>C:\Users\Schitan996\Desktop\TC_2_090412\src\server\game\Entities\Player\Player.cpp(25574): error C3861: 'GetGUIDLow' : identificateur introuvable
3>C:\Users\Schitan996\Desktop\TC_2_090412\src\server\game\Entities\Player\Player.cpp(25578): error C3861: 'GetGUIDLow' : identificateur introuvable
3>C:\Users\Schitan996\Desktop\TC_2_090412\src\server\game\Entities\Player\Player.cpp(25581): error C2227: la partie gauche de '->GetDifficulty' doit pointer vers un type class/struct/union/générique
3>          le type est ''unknown-type''
3>C:\Users\Schitan996\Desktop\TC_2_090412\src\server\game\Entities\Player\Player.cpp(25581): error C3861: 'GetMap' : identificateur introuvable
3>C:\Users\Schitan996\Desktop\TC_2_090412\src\server\game\Entities\Player\Player.cpp(25587): error C2065: 'm_wowarmory_feeds' : identificateur non déclaré
3>C:\Users\Schitan996\Desktop\TC_2_090412\src\server\game\Entities\Player\Player.cpp(25587): error C2228: la partie gauche de '.push_back' doit avoir un class/struct/union
3>          le type est ''unknown-type''
4>------ Début de la génération : Projet : worldserver, Configuration : Release Win32 ------
4>LINK : fatal error LNK1181: impossible d'ouvrir le fichier en entrée '..\game\Release\game.lib'
5>------ Début de la génération : Projet : ALL_BUILD, Configuration : Release Win32 ------
5>  Build all projects
========== Génération : 3 a réussi, 2 a échoué, 9 mis à jour, 0 a été ignoré ==========

**Comment by Seejayz** [comment]
Hold it, im looking into it.

**Comment by Seejayz** [comment]
https://github.com/Seejayz/WorldofwarcraftArmory/commit/5fbe20a0b4a77169c93a2f16f3477391bfe19e63
