### ISSUE TITLE
Bug with item in google chrome

### ISSUE THREAD

**Issue by omega500** [Seejayz/WorldofwarcraftArmory#3]
Hi !
Thx for the fixed patch.
I have a problem with google-chrome, when i put my cursor on an item's player, that doesn't work .
But on firefox that work very fine !
Do you have any idea to fix that ?

screenshot : http://legend-menethil.com/images/bug.jpg
Paint ultraskillz

**Comment by Seejayz** [comment]
Google chrome causes this issue, not the Armory.
